ktlint: test

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/bash
-
-echo "Running git pre-commit hook"
-
+#
+#echo "Running git pre-commit hook"
+#
 #CHANGED_FILES="$(git --no-pager diff --name-only --cached --diff-filter=ACMRTUXB --relative | grep '\.kt[s"]\?$')"
 #
 #if [ -z "$CHANGED_FILES" ]; then
@@ -20,11 +20,38 @@ echo "Running git pre-commit hook"
 #    done
 #  fi
 #fi
+#
+##git diff --name-only -z --cached --relative -- '*.kt' '*.kts' | ./gradlew ktlintFormat --relative --patterns-from-stdin=''
+##
+##STATUS=$?
+##
+### return 1 if fails
+##[ $STATUS -ne 0 ] && exit 1
+##exit 0
 
-git diff --name-only -z --cached --relative -- '*.kt' '*.kts' | ./gradlew ktlintFormat --relative --patterns-from-stdin=''
+##!/bin/sh
 
-STATUS=$?
+######## KTLINT-GRADLE HOOK START ########
 
-# return 1 if fails
-[ $STATUS -ne 0 ] && exit 1
-exit 0
+CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.kts|\.kt/ { print $2}')"
+
+if [ -z "$CHANGED_FILES" ]; then
+    echo "No Kotlin staged files."
+    exit 0
+fi;
+
+echo "Running ktlint over these files:"
+echo "$CHANGED_FILES"
+
+./gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"
+
+echo "Completed ktlint run."
+
+echo "$CHANGED_FILES" | while read -r file; do
+    if [ -f $file ]; then
+        git add $file
+    fi
+done
+
+echo "Completed ktlint hook."
+######## KTLINT-GRADLE HOOK END ########
