feat: update github actions with ktlint

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -64,6 +64,31 @@ jobs :
             exit 1
           fi 
 
+  kt-lint:
+    needs: test
+    runs-on: macOS-latest
+
+    steps:
+      - uses: action/checkout@v3
+      - name: set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: 17
+          distribution: "temurin"
+          cache: gradle
+
+      - name: Run ktlintFormat
+        run: ./gradlew ktlintFormat --stacktrace
+
+      - name: Check unit tests status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "KtlintFormat passed."
+          else
+            echo "KtlintFormat failed."
+            exit 1
+          fi 
+
 #      - name: Upload built artifact
 #        uses: actions/upload-artifact@v3.1.3
 #        with:
